# SPDX-License-Identifier: Apache-2.0
"""Utilities for deterministic ObjectKey encoding and backend-key mapping."""

# Standard
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import struct

# Third Party
import torch

# First Party
from lmcache.utils import CacheEngineKey
from lmcache.v1.distributed.api import ObjectKey

_CODEC_VERSION = 1


@dataclass(frozen=True)
class PackedObjectKey:
    version: int
    model_name: str
    kv_rank: int
    chunk_hash: bytes


def pack_object_key(key: ObjectKey) -> bytes:
    """Pack ObjectKey into a stable versioned byte representation."""
    model_bytes = key.model_name.encode("utf-8")
    hash_bytes = bytes(key.chunk_hash)

    if len(model_bytes) > 0xFFFF:
        raise ValueError("ObjectKey model_name is too large to pack")
    if len(hash_bytes) > 0xFFFF:
        raise ValueError("ObjectKey chunk_hash is too large to pack")

    parts = [
        struct.pack("!B", _CODEC_VERSION),
        struct.pack("!H", len(model_bytes)),
        model_bytes,
        struct.pack("!I", key.kv_rank & 0xFFFFFFFF),
        struct.pack("!H", len(hash_bytes)),
        hash_bytes,
    ]
    return b"".join(parts)


def unpack_object_key(payload: bytes) -> PackedObjectKey:
    """Unpack bytes generated by pack_object_key()."""
    view = memoryview(payload)
    if len(view) < 1 + 2 + 4 + 2:
        raise ValueError("Packed ObjectKey payload too short")

    offset = 0
    version = struct.unpack_from("!B", view, offset)[0]
    offset += 1
    if version != _CODEC_VERSION:
        raise ValueError(f"Unsupported ObjectKey codec version: {version}")

    model_len = struct.unpack_from("!H", view, offset)[0]
    offset += 2
    if len(view) < offset + model_len + 4 + 2:
        raise ValueError("Packed ObjectKey model_name length is invalid")

    model_name = bytes(view[offset : offset + model_len]).decode("utf-8")
    offset += model_len

    kv_rank = struct.unpack_from("!I", view, offset)[0]
    offset += 4

    hash_len = struct.unpack_from("!H", view, offset)[0]
    offset += 2
    if len(view) != offset + hash_len:
        raise ValueError("Packed ObjectKey chunk_hash length is invalid")

    chunk_hash = bytes(view[offset : offset + hash_len])
    return PackedObjectKey(
        version=version,
        model_name=model_name,
        kv_rank=kv_rank,
        chunk_hash=chunk_hash,
    )


def object_key_to_cache_key(key: ObjectKey) -> CacheEngineKey:
    """Convert ObjectKey to a deterministic CacheEngineKey."""
    packed = pack_object_key(key)
    digest = hashlib.blake2b(packed, digest_size=8).digest()
    chunk_hash_u64 = int.from_bytes(digest, byteorder="big", signed=False)

    request_configs = {
        "lmcache.tag.object_key_codec": str(_CODEC_VERSION),
        "lmcache.tag.object_kv_rank": str(int(key.kv_rank)),
        "lmcache.tag.object_chunk_hash_hex": key.chunk_hash.hex(),
    }

    return CacheEngineKey(
        model_name=key.model_name,
        world_size=1,
        worker_id=int(key.kv_rank),
        chunk_hash=chunk_hash_u64,
        dtype=torch.uint8,
        request_configs=request_configs,
    )


def cache_key_to_object_key(cache_key: CacheEngineKey) -> ObjectKey | None:
    """Best-effort reverse mapping for keys created by object_key_to_cache_key."""
    request_configs = cache_key.request_configs or {}
    kv_rank_raw = request_configs.get("lmcache.tag.object_kv_rank")
    chunk_hash_hex = request_configs.get("lmcache.tag.object_chunk_hash_hex")
    if kv_rank_raw is None or chunk_hash_hex is None:
        return None

    try:
        kv_rank = int(kv_rank_raw)
        chunk_hash = bytes.fromhex(chunk_hash_hex)
    except Exception:
        return None

    return ObjectKey(
        chunk_hash=chunk_hash,
        model_name=cache_key.model_name,
        kv_rank=kv_rank,
    )
